# The basic requirements for developing xlcompose docs
name: xlc_docs

channels:
  - defaults
  - conda-forge

dependencies:
  - git
  - pip
  - xlsxwriter>=1.1.8
  - pandas
  - pyyaml
  - jinja2
  - sphinx
  - numpydoc
  - pip:
    - git+https://github.com/jbogaardt/xlcompose/
