name: Unit Tests

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  linux:
    name: (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest'] #, 'macos-latest', 'windows-latest']
        python-version: ['3.7'] #, '2.7']
    steps:
      - uses: actions/checkout@v1
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Install repo and dependencies
        shell: bash -l {0}
        run: |
          conda env create --file environment-test.yaml;
          conda activate xlc_test
          python setup.py develop
          pytest --cov=. --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
